### ISSUE TITLE
Create a file for double linked list operations

### ISSUE THREAD

**Issue by firefire-iceice** [rishitc/Competitive-Programming-Library-Functions#3]

**Comment by marcotaranta** [comment]
Hello, can I have more details on what is needed?

**Comment by rishitc** [comment]
The operations you can create programs for are:
1. Reversing a Doubly linked list
1. Sorting a doubly-linked list
1. Returning a slice of a Doubly Linked list
     1. Negative indexing is should be supported
1. Swapping two elements of a doubly-linked list, given their indices using pointers and no temporary pointer
       1. Negative indexing should be supported

**Comment by marcotaranta** [comment]
Nice, can I give it a go? I will follow the example in single linked lists ok?

**Comment by firefire-iceice** [comment]
Sure go ahead!
Make sure to make a separate folder for doubly linked list
